---
title: "Literature Review"
output: bookdown::html_document2
bibliography: references.bib
---

```{r setup, include=FALSE}
library(stargazer)
knitr::opts_chunk$set(echo = TRUE)
```


# A Tale of Two Cities, the paper by @young

The paper by Alwyn Young can be located in the pdf file [young.pdf](Literature/Tale/young.pdf). The paper can also be accessed by the [link](https://www.journals.uchicago.edu/doi/abs/10.1086/654183).

In his paper, he use **The Translog Index of Total Factor Productivity Growth** to estimate the Total Factor Productivity Growth in Hong Kong and Singapore.



# A note on references

The references @correa_2009 and @young are cited.

@correa_2009 is an example in the original `references.bib` file. @young was added by me. The details of the bio data of this article in the `references.bib` file can be downloaded from the website of the article by selecting `BibTex` and then copy and paste with some minor modifications. 


Other reference: @ikemoto, and article by [Yukio Ikemoto](Literature/ikemoto/TheDevelopingEconomies_IKEMOTO.pdf)



## Reference